// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	VideoID uuid.UUID
	Content pgtype.Text
}

type Friend struct {
	UserId1   uuid.UUID
	UserId2   uuid.UUID
	Confirmed int32
}

type Session struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID            uuid.UUID
	Username      string
	Email         string
	Password      string
	Description   pgtype.Text
	ProfilePicUrl pgtype.Text
}

type Video struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	VideoUrl  string
	Filename  string
	Type      pgtype.Text
}
